---
- name: Generate {{ item }} private key
  openssl_privatekey:
    path: /etc/ssl/letsencrypt/{{ item }}.key
    size: 2048
  tags: certs

- name: Generate {{ item }} csr
  openssl_csr:
    path: /etc/ssl/letsencrypt/{{ item }}.csr
    common_name: "{{ item }}"
    privatekey_path: /etc/ssl/letsencrypt/{{ item }}.key
  tags: certs

- name: Letsencrypt {{ item }} Step 1
  acme_certificate:
    account_email: kelsin@valefor.com
    account_key_src: /etc/ssl/letsencrypt.key
    csr: /etc/ssl/letsencrypt/{{ item }}.csr
    dest: /etc/ssl/letsencrypt/{{ item }}.pem
    fullchain_dest: /etc/ssl/letsencrypt/{{ item }}-full.pem
    acme_version: 1
    remaining_days: 30
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
  register: letsencrypt_challenge
  tags: certs

- name: Create {{ item }} challenge file
  copy:
    dest: /var/www/html/{{ letsencrypt_challenge['challenge_data'][item]['http-01']['resource'] }}
    content: "{{ letsencrypt_challenge['challenge_data'][item]['http-01']['resource_value'] }}"
  when: letsencrypt_challenge is changed
  tags: certs

- name: Letsencrypt {{ item }} Step 2
  acme_certificate:
    account_email: kelsin@valefor.com
    account_key_src: /etc/ssl/letsencrypt.key
    csr: /etc/ssl/letsencrypt/{{ item }}.csr
    dest: /etc/ssl/letsencrypt/{{ item }}.pem
    fullchain_dest: /etc/ssl/letsencrypt/{{ item }}-full.pem
    data: "{{ letsencrypt_challenge }}"
    acme_version: 1
    remaining_days: 30
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
  tags: certs

- name: remove challenge file
  file:
    path: /var/www/html/{{ letsencrypt_challenge['challenge_data'][item]['http-01']['resource'] }}
    state: absent
  when: letsencrypt_challenge is changed
  tags: certs
