---
- name: Install web packages
  apt:
    name:
        - ca-certificates
        - curl
  tags:
      - caddy
      - packages

- name: Install caddy
  shell: "CADDY_TELEMETRY=on curl https://getcaddy.com | bash -s personal http.cors,http.jwt"
  args:
    creates: /usr/local/bin/caddy
  tags: caddy

- name: Setup caddy group
  group:
    name: caddy
  tags: caddy

- name: Setup caddy user
  user:
    name: caddy
    groups: caddy
    shell: /usr/sbin/nologin
    home: /var/www
    create_home: no
  tags: caddy

- name: Setup caddy binary permissions
  file:
    path: /usr/local/bin/caddy
    state: file
    mode: 0755
    owner: root
    group: root
  tags: caddy

- name: Setup caddy config folder
  file:
    path: /etc/caddy
    state: directory
    mode: 0775
    owner: root
    group: caddy
  tags: caddy

- name: Setup caddy sites folder
  file:
    path: /etc/caddy/sites
    state: directory
    mode: 0775
    owner: caddy
    group: caddy
  tags: caddy

- name: Setup caddy ssl folder
  file:
    path: /etc/caddy/ssl
    state: directory
    mode: 0770
    owner: caddy
    group: caddy
  tags: caddy

- name: Setup caddy root folder
  file:
    path: /var/www
    state: directory
    mode: 0775
    owner: caddy
    group: caddy
  tags: caddy

- name: Install Caddyfile
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: 0644
  notify: reload caddy
  tags: caddy

- name: Install new caddy site files
  copy:
    src: sites/
    dest: /etc/caddy/sites
    owner: caddy
    group: caddy
    mode: 0644
  notify: reload caddy
  tags:
      - caddy
      - sites

- name: Install the caddy service
  copy:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    mode: 0644
    owner: root
    group: root
  tags: caddy

- name: Enable the caddy service
  systemd:
    name: caddy
    state: started
    enabled: yes
    daemon_reload: yes
  tags: caddy

- include_tasks: wordpress.yml
  tags:
      - sites
      - wordpress

- include_tasks: login.yml
  tags:
      - sites
      - login

- include_tasks: pnp.yml
  tags:
      - sites
      - pnp
