---
- name: Create wordpress config folder
  file:
    path: /etc/wordpress
    state: directory
    owner: root
    group: root
    mode: 0770
  tags:
      - sites
      - wordpress

- name: Create the uploads.ini file
  copy:
    src: wordpress/uploads.ini
    dest: /etc/wordpress/uploads.ini
    owner: root
    group: root
    mode: 0644
  tags:
      - sites
      - wordpress

- name: Create the wp-content volume
  docker_volume:
    name: wp-content
  tags:
      - sites
      - wordpress

- name: Set permissions on the wp-content volume
  file:
    path: /var/lib/docker/volumes/wp-content/_data
    owner: "33"
    group: "33"
    recurse: yes
    state: directory
  tags:
      - sites
      - wordpress

- name: Install our klatch wordpress plugin
  copy:
    src: wordpress/klatch.php
    dest: /var/lib/docker/volumes/wp-content/_data/plugins/klatch.php
    owner: "33"
    group: "33"
    mode: 0644
  tags:
      - sites
      - wordpress

- name: Create the wordpress container
  docker_container:
    name: wordpress
    image: wordpress:5
    ports: 8080:80
    env_file: /etc/wordpress/env
    networks_cli_compatible: no
    etc_hosts:
      smtp: 172.17.0.1
    networks:
        - name: wordpress
    volumes:
        - "wp-content:/var/www/html/wp-content/"
        - "/etc/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
  tags:
      - sites
      - wordpress
