---
- name: Install docker repo packages
  apt:
    name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
  tags:
      - docker
      - packages

- name: Install docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags: docker

- name: Install docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
  tags: docker

- name: Install docker packages
  apt:
    name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  tags: docker

- name: Start the docker service
  service: name=docker state=started enabled=yes
  tags: docker
